# Generated by Django 3.1.5 on 2021-01-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room_code',
            field=models.CharField(max_length=25),
        ),
    ]
